name: '.Platform: Update ReadMe Module Tables'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - 'arm/**/deploy.bicep'
      - 'arm/**/deploy.json'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - name: pipelinePrincipalGitUserName
    value: 'CARMLPipelinePrincipal'
  - name: pipelinePrincipalGitUserEmail
    value: 'CARML@noreply.github.com'

jobs:
  - job: Update module tables
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        persistCredentials: true
      - task: PowerShell@2
        displayName: 'Update general ReadMe'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            Write-Verbose $(System.DefaultWorkingDirectory)
            Write-Verbose $(Build.Repository.Name)
            # . (Join-Path '$(System.DefaultWorkingDirectory)' 'utilities' 'tools' 'Set-GitHubReadMeModuleTable.ps1')

            # $functionInput = @{
            #   ModulesPath    = Join-Path '$(System.DefaultWorkingDirectory)' 'arm'
            #   FilePath       = Join-Path '$(System.DefaultWorkingDirectory)' 'README.md'
            #   Organization   = ($(Build.Repository.Name)).split('/')[0]
            #   RepositoryName = '$(Build.Repository.Name)'
            #   ColumnsInOrder = @('Name', 'Status')
            #   SortByColumn   = 'Name'
            # }

            # Write-Verbose "Invoke task with" -Verbose
            # Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            # Set-GitHubReadMeModuleTable @functionInput -Verbose
