name: '.Platform: Sync Docs/Wiki'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'docs/wiki/**'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - name: pipelinePrincipalGitUserName
    value: 'CARMLPipelinePrincipal'
  - name: pipelinePrincipalGitUserEmail
    value: 'CARML@noreply.github.com'
  - name: wikiRepository
    value: '$(Build.Repository.Uri).wiki'

jobs:
  - job: Update_module_tables
    pool:
      ${{ if ne('$(vmImage)', '') }}:
        vmImage: '$(vmImage)'
      ${{ if ne('$(poolName)', '') }}:
        name: '$(poolName)'
    steps:
      - checkout: self
        displayName: Checkout Source Repo
        persistCredentials: true
      # Create a variable
      - task: PowerShell@2
        displayName: 'Update general ReadMe'
        name: setvarStep
        inputs:
          targetType: inline
          pwsh: true
          script: |
            $wikiRepository = '$(Build.Repository.Uri)' + '.wiki'
            Write-Verbose $wikiRepository -Verbose
            echo "##vso[task.setvariable variable=wikiRepository;isOutput=true]$wikiRepository" # remember to use double quotes
            Write-Verbose $(myOutputVar) -Verbose
      - task: PowerShell@2
        displayName: 'Update general ReadMe'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            Write-Verbose $(setvarStep.myOutputVar) -Verbose
