name: '.Platform: Sync Docs/Wiki'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'docs/wiki/**'

variables:
  - group: 'test'
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - name: pipelinePrincipalGitUserName
    value: 'CARMLPipelinePrincipal'
  - name: pipelinePrincipalGitUserEmail
    value: 'CARML@noreply.github.com'
  - name: wikiRepository
    value: '$(Build.Repository.Uri).wiki'

jobs:
  - job: Update_module_tables
    pool:
      ${{ if ne('$(vmImage)', '') }}:
        vmImage: '$(vmImage)'
      ${{ if ne('$(poolName)', '') }}:
        name: '$(poolName)'
    steps:
      - checkout: self
        displayName: Checkout Source Repo
        persistCredentials: true
      # Create a variable
      - task: PowerShell@2
        displayName: 'Checkout Wiki Repo'
        name: setvarStep
        inputs:
          targetType: inline
          pwsh: true
          script: |
            git config --global user.email '$(pipelinePrincipalGitUserEmail)'
            git config --global user.name '$(pipelinePrincipalGitUserName)'
            $repositoryEndpoint= 'https://' + '$(PAT)' + '@github.com/' + '$(Build.Repository.Name)' + '.wiki'
            Write-Verbose $repositoryEndpoint -Verbose
            git clone $repositoryEndpoint
            ls
            cd '$(System.DefaultWorkingDirectory)'
            ls

      # - task: PowerShell@2
      #   displayName: 'Sync docs/wiki Into Wiki Repo'
      #   name: setvarStep
      #   inputs:
      #     targetType: inline
      #     pwsh: true
      #     script: |
      #       $docsPath = Join-Path '$(System.DefaultWorkingDirectory)' 'docs' 'wiki'
      #       $wikiRepo = Join-Path '$(System.DefaultWorkingDirectory)' '$(Build.Repository.Name)' '.wiki'
      #       rsync -avzr --delete --exclude='.git/' $docsPath "${{ env.wiki_target_repo }}"
